### PR TITLE
Merge branch 'main' of https://github.com/nwatx/nwatx-blog into main

### PR DESCRIPTION
**Pull request by nwatx**
@dongliu0426

### CODE REVIEW

**Comment by dongliu0426** [comment]
whats wrong with the former?

**Comment by nwatx** [comment]
nothing just change MOD -> 1e9+7 instead

**Comment by nwatx** [comment]
and add spacing between include bits and using namespace std for cnosnistency

**Comment by dongliu0426** [comment]
ok sure

**Comment by nwatx** [comment]
:yay:

**Pull request merged**
